project:
  title: "Prospectus" # Project title
  type: website
  execute-dir: project
  render:
    - index.qmd
    - process/1_acquire.qmd
    - process/2_curate.qmd
    - process/3_transform.qmd
    - process/4_analyze.qmd
    - reports/

website:
  page-navigation: true # Enable page navigation
  reader-mode: true # Enable reader mode
  site-url: "https://francojc-lin380s24.github.io/project/" # Website URL
  repo-url: https://github.com/francojc-lin380s24/project/ # Repository URL
  repo-actions: [source, issue] # Repository actions
  sidebar:
    style: "docked" # Sidebar style
    search: true # Enable search
    collapse-level: 2 # Initial sidebar collapse level
    contents: # Sidebar contents
      - index.qmd
      - section: "Process"
        contents: process/*

      - section: "Reports"
        contents: reports/*
    tools:
      - icon: github
        href: https://github.com/username/repo

bibliography: bibliography.bib # Bibliography file

format:
  html:
    theme: journal
    toc: true # Enable table of contents

execute:
  freeze: auto # only render documents that have changed
